cat << EOF > /data/ocp/ocp-install/oauth.yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: local-provider
    type: HTPasswd
	mappingMethod: claim
    htpasswd:
      fileData:
        name: htpass-secret
EOF